### ISSUE TITLE
You must be logged in to use triple.

### ISSUE THREAD

**Issue by devmoreno** [tonylukasavage/triple#97]
I been getting this error because triple uses the titanium cli to login. The titanium cli login command was deprecated and now uses the appc instead. I am currently logged in on my appc but triple still says I am not logged in.

![screenshot 2015-09-09 11 31 04](https://cloud.githubusercontent.com/assets/7477701/9766333/4e45d5f4-56e6-11e5-9916-f2220bf17187.png)

**Comment by Sophrinix** [comment]
Thanks for letting us know.

(This appears to be the problem)[https://github.com/tonylukasavage/triple/blob/3513d5266ce32584636569e8bb459d1b233f0b70/lib/triple.js#L70

We need to comment that out.. ideally the whole async block needs to go. I'll try to touch this tomorrow if I get a chance. @untward do you have a second to comment out that bit of code and do a pull request?

**Comment by Sophrinix** [comment]
try pulling this down and running it. it should be fixed now. I decided to just deal with it.

**Comment by Sophrinix** [comment]
okay now I have confidence in this issue being fixed.
make sure you delete your .triple (note the dot ) in whatever directory you were running triple from.

I will leave this open so that you can confirm on your computer that this works.

**Comment by Sophrinix** [comment]
I'm going to close this issue by saturday morning. If it is still an issue then please feel free to comment and I'll re open it.
